spring:
  application:
    name: github-repo
application:
  github:
    api:
      base-url: "${GITHUB_API_BASE_URL:https://api.github.com}"
      accept-header: "${GITHUB_API_ACCEPT_HEADER:application/vnd.github+json}"
      token: "${GITHUB_API_TOKEN:}"
      version: "${GITHUB_API_VERSION:2022-11-28}"
